### ISSUE TITLE
#database-issues issue submitter 

### ISSUE THREAD

**Issue by log-ical** [sourcejump/discord-bot#14]
![image](https://user-images.githubusercontent.com/42725021/171954734-188eb7d9-0194-4673-b8ef-8551d6f0b360.png)

> 
> Map name: bhop_monster_jam
> Issue: Short explanation of the issue. Tier {insert number here}, bad zones, cheated time etc.
> Screenshot/Video: Optionally attach or link a screenshot/video to help explain the issue.

Create a modal for creating issues for the database-issues channel. Only problem is you can't attach images or videos with modals or slash commands so people will need to use links.

**Comment by pxbhop** [comment]
I can work on this

**Comment by pxbhop** [comment]
Before I get started on this, just want to check the flow of it. 
- User runs command in database-issues (can actually restrict permissions for this channel to only using commands and not sending messages I believe, which could be done)
- Modal appears with fields for map name, issue, screenshot/video link 
- Embed is created in channel for a database manager to react to with a tick or a cross
OR
- Create message in a database manager chat with embed and confirmation buttons (see #15 )
- On button press, send embed to database-issues with details and outcome (potentially with the ability to add reasoning if denied, unsure if this is possible)

**Comment by ecsr** [comment]
The flow should be something like this:

- User runs the command and a modal appears with map, issue and screenshot/video url (optional) fields.
- When the user presses submit an embed message with all the details is sent to the #database-issues channel. This message can have two buttons, one for marking it as resolved and one for denying it.

**Comment by ecsr** [comment]
#database-issues channel has been replaced with a "forum channel" so this is not really needed anymore.
