### ISSUE TITLE
Greetings

### ISSUE THREAD

**Issue by ecsr** [sourcejump/discord-bot#3]
Listen to messages (morning, night, etc.) when tagged in a message. Tag same user in same channel with random greeting.

![greetings](https://user-images.githubusercontent.com/46975257/168451153-65b8bbf6-c6c8-4988-8283-78408a72f24d.png)

**Comment by log-ical** [comment]
Might as well take care of this real quick. Sign me up ✋

**Comment by log-ical** [comment]
#5
