### ISSUE TITLE
Record check command

### ISSUE THREAD

**Issue by ecsr** [sourcejump/discord-bot#4]
A command for checking global records on the specified map. [SourceJump API](https://sourcejump.net/api) should be used for retrieving the record and other information.

Current implementation just listen to messages sent in a channel but a slash command (`/record {map}`) might be a better solution for this?

![record](https://user-images.githubusercontent.com/46975257/168451300-af3da049-3fa9-483c-9b08-dad09b663dbe.png)

**Comment by pxbhop** [comment]
Will work on this now

**Comment by pxbhop** [comment]
#6
