### ISSUE TITLE
GameBanana watcher

### ISSUE THREAD

**Issue by ecsr** [sourcejump/discord-bot#7]
Check [GameBanana](https://gamebanana.com) for new CS:S and CS:GO bhop/kz maps, if there is a new submission send a message to a specific channel.

![gamebanana](https://user-images.githubusercontent.com/46975257/168484372-8fe1c79b-6a8c-4b88-aa54-1bb59712ac88.png)

**Comment by log-ical** [comment]
You can go ahead and assign this one to me

**Comment by log-ical** [comment]
#9
