### ISSUE TITLE
Ban appeal command

### ISSUE THREAD

**Issue by ecsr** [sourcejump/discord-bot#8]
Let players submit ban appeals for the global database by using `/banappeal` or `/appeal`. The command should show a [modal window](https://github.com/discordjs/discord.js/pull/7023) where the player can fill in their name, steamid and appeal reason, when they click submit the appeal should be sent to a channel where admins can review it.

**Comment by log-ical** [comment]
I'll handle this one.

Question though, do we want the admins to be able to do anything such as accepting the appeal through the bot?

**Comment by ecsr** [comment]
Yes having a approve and reject button which send a message to the person who made the appeal with the decision would be nice.
